stages:
  - build
  - deploy

build:
  stage: build
  script:
    - echo "Building Docker images"
    - docker-compose build

# TODO: add a test stage

deploy:
  stage: deploy
  script:
    - echo "Deploying Docker Compose app"
    - docker-compose up -d