stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - docker-compose -p ci -f docker-compose.yml -f docker-compose.tests.yml build

test:
  stage: test
  
  script:
    - chmod +x ./test.sh
    - ./test.sh

deploy:
  stage: deploy
  script:
    - docker-compose -f docker-compose.yml up -d