services:
  node-service:
    build: ./service1
    environment:
      - PORT=3000 # check why this makes it work
    networks:
      - mynetwork

  golang-service:
    build: ./service2
    expose:
      - "3001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - mynetwork

  frontend:
    build: ./frontend
    ports:
      - "8198:80"
    networks:
      - mynetwork
    environment:
      - BASIC_USERNAME=admin
      - BASIC_PASSWORD=admin

  api-gateway:
    build: ./api-gateway
    ports:
      - "8197:8197"
    networks:
      - mynetwork
    environment:
      - AUTH_USERNAME=admin
      - AUTH_PASSWORD=admin

networks:
  mynetwork:
    driver: bridge
