services:
  tests:
    image: node:latest
    volumes:
      - ./tests:/code
    working_dir: /code
    networks:
      - ci_mynetwork
    environment:
      host: "http://api-gateway:8197"
    restart: "no"
    tty: true
    
    command: bash -c "npm i && while ping -c1 api-gateway &>/dev/null; do sleep 1; done; echo 'api-gateway service is up' && npm test"

networks:
  ci_mynetwork:
    external: true