http {
    include mime.types;
    
    upstream backend {
        server node-service-1:3000;
        server node-service-2:3000;
        server node-service-3:3000;
    }
    
    server {
        listen 80;
        location / {
            auth_basic "Restricted Access";
            auth_basic_user_file .htpasswd;

            root /usr/share/nginx;
            try_files $uri /dist/index.html =404;
        }
        location /assets {
            alias /usr/share/nginx/dist/assets;
        }

        location /api {
            proxy_pass http://backend;
        }
    }
}

events {}